### ISSUE TITLE
Jump to definition in JSX goes to wrong file when there's a type error

### ISSUE THREAD

**Issue by bsansouci** [rescript-lang/rescript-vscode#156]
Hey all! I'm testing the beta from here https://forum.rescript-lang.org/t/ann-new-rescript-vscode-beta-testers-needed/1518

Everything works great! But when I introduce a type error, and then it jumps to some different and unrelated file. Here's the code that type checks, and I can cmd+click on `ThirdPane` to get to the right file and place.
```rescript
<ThirdPane>
        <div>
          {ReasonReact.string(unwrapWithDefault(obj.headline, "[No headline]"))}
        </div>
</ThirdPane>
```

If I introduce my type error by switching `obj.headline` to an int `10`:
```rescript
<ThirdPane>
        <div>
          {ReasonReact.string(unwrapWithDefault(10, "[No headline]"))}
        </div>
</ThirdPane>
```
then cmd+click on `ThirdPane` will lead me to `React.re` line 3, which is the external called `null`.

**Comment by bsansouci** [comment]
cc @rickyvetter

**Comment by cristianoc** [comment]
If a file does not compile, then the compiler artifacts are stale, and indeed you can jump to the wrong location.
Normally, a type error stops the production of compiler artifacts for that file, with partial output. The partial output stops at the compiler error. In this case, a bunch of code is generated by the PPX, so it's likely that parts of the generated code leads does compile fine and part has a type error. Then the part that compiles fine is the one responsible for the wrong jump to location.

Context, the ppx defines several symbols at exactly the same location, and the editor support needs some heuristics to figure out which one is meant to be used. In this case, there's probably a subset of symbols generated at the same location than usual (because one of them fails to type check).

Seems likely this should go away if we can generate exactly one symbol at non-dummy location from the ppx. That's a hypothesis, already discussed, but not tested yet.

**Comment by cristianoc** [comment]
@bsansouci thanks for being our master discoverer of corner cases.

**Comment by bsansouci** [comment]
Wow thanks for the explanation! So is this mostly a problem when cmd+clicking JSX tags right? 
This would be a bigger issue for me if it happened in other places, because my code tends to be in a state where it's not type checking yet and I like to jump around.

**Comment by cristianoc** [comment]
If there's a problem with jump-to-loc, likely there's a problem with hover too. E.g. it will hover on `makeProps` not `make` (or the other way round).

**Comment by cristianoc** [comment]
Feel free to reopen with a self-contained repro.
A bunch of related issues are fixed, no not sure this still exists.
