### ISSUE TITLE
Highlighting of JSX tags

### ISSUE THREAD

**Issue by jfrolich** [rescript-lang/rescript-vscode#21]
Hi,

I'm testing out the new 1.0 release of the plugin and I am very impressed! It might be already on the radar, but I didn't see an issue for it; the JSX tags are currently not highlighted making the source code harder to read IMO. See attached code sample for the difference:

![image](https://user-images.githubusercontent.com/579279/99932122-140fff80-2d92-11eb-90c4-3b9ff38cc4cd.png)

**Comment by tkovs** [comment]
Here it is working for my own components

![image](https://user-images.githubusercontent.com/8717661/100301163-585bf500-2f76-11eb-8184-49986649677f.png)

**Comment by jfrolich** [comment]
Interesting! That is not working for me. What version of the extension are you using?

**Comment by tkovs** [comment]
> Interesting! That is not working for me. What version of the extension are you using?

![image](https://user-images.githubusercontent.com/8717661/100530342-88ea9b80-31cf-11eb-87cb-c40287188181.png)

**Comment by jfrolich** [comment]
I found out that it is just that my theme didn't color the `entity.name.namespace`. Many themes do not, because I had this hypothesis that my theme wasn't displaying them and swapped a few themes and they also didn't. Dark+ does however. You can also add the value in the settings:

```jsonc
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "name": "JSX",
        "scope": ["entity.name.namespace"],
        "settings": {
          "foreground": "#80CBC4"
        }
      },
      // you might also want to set this for polymorphic variants
      {
        "name": "other",
        "scope": ["punctuation.definition.keyword"],
        "settings": {
          "foreground": "#f87086"
        }
      }
    ]
  }
```

**Comment by Faliszek** [comment]
@jfrolich thanks for the solution, i also wanted to highlight in my theme, element and their attributes in jsx but I found that with actual grammar this it is not possible(?).
What i mean is, in .re file with ocaml-platform extension when i check it with `Cmd + Shift + P` and pick `DM: Inspect editor and scopes` i get something like this when checking <ul className="bg-white">:

<img width="546" alt="Zrzut ekranu 2020-12-8 o 01 29 24" src="https://user-images.githubusercontent.com/19210348/101421751-58a0ac80-38f5-11eb-99a5-4fc8e4626a9c.png">
<img width="547" alt="Zrzut ekranu 2020-12-8 o 01 29 18" src="https://user-images.githubusercontent.com/19210348/101421754-5c343380-38f5-11eb-9153-10a18bfa848c.png">

but right now they are not assigned to any scope

<img width="472" alt="Zrzut ekranu 2020-12-8 o 01 29 49" src="https://user-images.githubusercontent.com/19210348/101421801-78d06b80-38f5-11eb-86df-0cb83838f164.png">
<img width="411" alt="Zrzut ekranu 2020-12-8 o 01 29 41" src="https://user-images.githubusercontent.com/19210348/101421807-7bcb5c00-38f5-11eb-85d6-297e18f34055.png">

Is it bug... or it is something that won't be implemented?

PS. I was thinking about it creating new issue, but this is also related to jsx so i thought it might good place to point that out. Because i think lot's of themes are decorating jsx in this manner

**Comment by Faliszek** [comment]
Hm, i can see that there is already pull request open with adding this feature

https://github.com/rescript-lang/rescript-vscode/pull/8/commits/52b9453cbd616f9ec08e008cb3ee7b0f10571c6c
