### ISSUE TITLE
Format width option

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/rescript-vscode#22]
Please add an option for configuring the format width (like Reason Language Server had with `reason_language_server.format_width`).

**Comment by amiralies** [comment]
what about having this on bsconfig so it's stable across editors / CI scripts.

cc/ @bobzhang @IwanKaramazow

**Comment by cknitt** [comment]
Yes, that would be even better!

**Comment by bobzhang** [comment]
@IwanKaramazow does our engine support this under the hood?
If so, what's the primary use case to have such option?

**Comment by cknitt** [comment]
@bobzhang sorry for answering in place of @IwanKaramazow. :wink:

Primary use case - well, different companies/projects/coding conventions use different line widths.
For example, we at CCA have set the line width to 120 in all our JavaScript and Reason projects.

Looking in the syntax repo, it seems to be supported already, see e.g. https://github.com/rescript-lang/syntax/blob/58e1fc9f6c962829ae4934590facc81cb5c9ed58/src/res_printer.mli#L16

**Comment by IwanKaramazow** [comment]
@bobzhang some more context, the printer uses an algorithm that breaks the layout based on the line width:
```rescript
// imagine having a line width of 20

// here the total length stays under 20:
apply(arg1, arg2)

// here the total length of 20 is exceeded, so the printer breaks the code over multiple lines
apply(
  arg1,
  arg2,
  arg3,
)
```
Our engine already supports this under the hood and now defaults to 100.
Different companies use different line widths, e.g. CCA warrants width 120, other companies prefer a width of 80 characters. It makes sense to expose this configuration option longer term, I think. It's hard to pick one line length that is "correct" for everyone…

**Comment by cknitt** [comment]
@bobzhang As the printer already supports this option, it would be really great if it could be exposed in the next bs-platform release. 🙏

**Comment by bobzhang** [comment]
The common practice seems to be adding a file like `.prettierrc` and the formatter respect the config from that file, this looks good to me

**Comment by amiralies** [comment]
Rescript's formatter is not as customizeable as something like prettier. the only option it has is print width so I'm not sure about introducing a new file like `.rescriptfmt`. on the other hand if you meant reusing prettier config, this might introduce another ambiguity since prettier is a different tool. my suggestion is putting the option in `bsconfig.json` or even `package.json` alongside with a command line flag (`bsc -format -width 80 foo.res`). what do you think?

**Comment by bobzhang** [comment]
we may add such `-width` after we migrate into subcommand mode which will take a while.
bsconfig.json is for build stuff. 
Something like .prettierrc seems more future proof since you can add more configures later

**Comment by TheSpyder** [comment]
I'm fine with adding a config file that only supports one option initially. Rather than `.prettierrc`, which might come with expectations the formatter doesn't implement, how about `.editorconfig` (https://editorconfig.org)? It has a [max line length](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#max_line_length) rule that quite a few editors support already.

**Comment by amiralies** [comment]
editorconfig has a different purpose. My point about not having a separate config file is that personally I don't like rescript's formatter to be much customizable in order to keep a consistent codestyle in community, this is really valuable IMO. If this is a goal of rescript's formatter, chance of having more configs is low. anyway, maybe Iwan is the best person who can answer this.

**Comment by TheSpyder** [comment]
I don't think it's that different, especially not when editorconfig already has a line length option.

Even if it's a dedicated `.resfmt` config file with a single option, that would still be better than a command line argument. It has been _so difficult_ over the years to apply a consistent customised `refmt` to a codebase worked on by multiple people.

> personally I don't like rescript's formatter to be much customizable in order to keep a consistent codestyle in community, this is really valuable IMO

I completely agree. I don't think any options other than width should exist. But there was a lot of pressure to add more to `refmt` so never say never.

**Comment by amiralies** [comment]
Having a command line option makes it possible to use this option outside of a project. So in an ideal situation both should exist, a command line option and a config file option.

> I completely agree. I don't think any options other than width should exist. But there was a lot of pressure to add more to `refmt` so never say never.

You're right. This might not be valuable for all people.

**Comment by imjoshellis** [comment]
Are there any updates on this? Anything we can do to help this move forward?

I'd love to be able to configure the break width as I've encountered more than a handful of pipes that are wrapping when I'd prefer them to reformat into multiple lines.

**Comment by chenglou** [comment]
We're currently not planning to expose a width option, though we're exploring a different way of making the printer do what the user wants.

**Comment by arcollector** [comment]
any updates about this?

**Comment by kswope** [comment]
Is there any progress on this?  I code on a laptop and don't have the best eyesight.  This is the only language I've ever used that forces me to scroll sideways when reading code.  Even worse, a default of 100 is just too much.
