### ISSUE TITLE
Hovers on record labels that are options in pattern matches does not expand record

### ISSUE THREAD

**Issue by zth** [rescript-lang/rescript-vscode#293]
I've noticed that hovering record labels (that are optionals) in pattern matches does not expand the record name they contain like most other hovers do. An example:

```rescript
type otherRecord = {id: string}

type someRecord = {someLabel: option<otherRecord>}

let someRecord = {
  someLabel: None,
}

switch someRecord {
| {someLabel: Some({id})} => Js.log(id)
| _ => ()
}
```

Hovering `{someLabel` in the pattern match gives `option<otherRecord>` (`otherRecord` is not included), but if the option is removed, hovering it gives (the definition of `otherRecord` is included):

```rescript
otherRecord
type otherRecord = {id: string}
```

**Comment by cristianoc** [comment]
Same is true for e.g. `z`:
```rescript
type someRecord = {
  someLabel: option<otherRecord>,
  z: (otherRecord, otherRecord),
}
```

Whenever a type is a compound type, there is no type expansion.

**Comment by cristianoc** [comment]
This is the expected behaviour.

**Comment by zth** [comment]
@cristianoc ahh right, so this is intended? If so, I guess I can close this?

**Comment by cristianoc** [comment]
@zth yes, nothing is set in stone, things could be arranged slightly differently too, but that's how they're arranged at the moment.

**Comment by cristianoc** [comment]
@zth indeed looks like the difference is not intentional, though it's explainable.
The second, more structured type, comes directly from the type system (every position in the AST has a type).
The former, less structured, is constructed. Starting from the record type, the `node` part is extracted. So what you see is the type from the point of view of the type declaration, rather than from the point of view of the use in the code. Some extra work would be required to construct a view from the perspective of the use in the code.

**Comment by zth** [comment]
@cristianoc excellent explanation, thank you!

**Comment by zth** [comment]
Solved in https://github.com/rescript-lang/rescript-vscode/commit/3bbdbee0187da005741d3311d64b1976eb6665a9
