### ISSUE TITLE
Declaration of an object with an empty key breaks language server.

### ISSUE THREAD

**Issue by not-rusty** [rescript-lang/rescript-vscode#299]
The following code:

```rescript
let test = {
  "": "dasfadsf",
}
```

Apparently breaks the language server if I save the file multiple times, as this vscode message says: 
`The ReScript Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.`

Is this expected? I have autosave activated with 200ms of margin, so the errors appear automatically in my screen. I believe this syntax shouldn't break the plugin.

rescript vscode version: 1.1.3
rescript version: 9.1.4

**Comment by not-rusty** [comment]
Related to https://github.com/rescript-lang/rescript-compiler/issues/3494

**Comment by amiralies** [comment]
This is becuase server is failing to parse the error message.

about empty object keys,
they are not supported at the moment so we should either make parser to disallow them or make the compiler support them, I think since the object access syntax is updated (`x[""]`) we can make  the compiler to allow them.

about the crash,
I think this is happening because the compiler log parser is throwing we should make that more resilient

**Comment by zth** [comment]
I cannot reproduce this as of now, so considering this solved. Feel free to reopen if not.
