### ISSUE TITLE
Feature request: add a toggle hide/show generated files, open generated file

### ISSUE THREAD

**Issue by prscoelho** [rescript-lang/rescript-vscode#413]
Hey guys.

I can hide generated files but I know this isn't considered best practice, you're supposed to look at the generated file to see if you've messed things up. But having a bunch of generated files in your tree list can be a noisy.

I thought of two commands that might be useful:

* Toggle show/hide generated files (is this something that's doable through lsp?)
* ~~Goto generated file for current buffer~~ nevermind, there's an open compiled command!

**Comment by zth** [comment]
VSCode just released a feature for grouping files together. That might be something we could implement for the VSCode extension specifically, to nest generated files collapsed under the source file:

https://code.visualstudio.com/updates/v1_67#_explorer-file-nesting

**Comment by Kingdutch** [comment]
No update to the extension is needed if people are willing to edit their own settings :D 

Open your VS Code settings and type "editor.filenesting", enable the feature and scroll down to patterns.

I've added two patterns:
![*.res pointing to ${capture}.mjs and *.resi pointing to ${capture.resi}](https://user-images.githubusercontent.com/327697/168044461-164d51ff-c166-47c9-9c8a-75aa1fe7f48e.png)

This nests implementations under interfaces if they're present and nests all generated files under the main ReScript file. Cleaning up the explorer nicely. As you can see for vite.resi it does not create nesting when both an interface and compiled file are present but instead keeps them both under the top level interface directly :D 

![image](https://user-images.githubusercontent.com/327697/168044718-083edcc9-27da-4f3d-972c-f52d93a44cee.png)

I think maybe the only added benefit for adding this to the `rescript-vscode` extension would be to automatically use the configured extension from `bsconfig.json`. However, if the extension were to hardcode this pattern we may actually decrease usability because people may want to enable nesting but omit certain patterns (e.g. I personally removed nesting `yarn.lock` under `package.json` because I prefer having those separate while using the nesting for ReScript).

**Comment by zth** [comment]
@Kingdutch very good point! Maybe we should just document how you can add that config yourself in the readme? Does anyone read the readme? 😄
