### ISSUE TITLE
New formatting producing syntax errors

### ISSUE THREAD

**Issue by remitbri** [rescript-lang/rescript-vscode#496]
Hello

I'm on a project using rescript 9.1.4, and I've been using the extension v1.3.0 for quite a while, with formatting on save enabled and without problems :) .
Since upgrading automatically to 1.4.0, I've noticed some minor new formatting (e.g `{...someRecord, foobar: foobar}` becoming `{...someRecord, foobar}`), which is surprising as I haven't migrated to a new rescript version. Painpoint: potentially having to reformat all my codebase without any "good reason" (quotes, quotes)? Hmm.

But much much more importantly, code like
```res
  @val
  external \"import": (
    @as("../SomeModule.mjs") _,
    unit,
  ) => Js.Promise.t<'a> = "import"
  let make = ReactLazy.make(() =>
    \"import"() |> Js.Promise.then_((module(SomeModule: SomeModuleType)) =>
      Js.Promise.resolve({"default": SomeModule.make})
    )
  )
```
is changed to
```res
 @val
  external import: (
    @as("../SomeModule.mjs") _,
    unit,
  ) => Js.Promise.t<'a> = "import"
  let make = ReactLazy.make(() =>
    import() |> Js.Promise.then_((module(SomeModule: SomeModuleType)) =>
      Js.Promise.resolve({"default": SomeModule.make})
    )
  )
```

and produces syntax errors 
1)
```
 `import` is a reserved keyword. Keywords need to be escaped: \"import"
 ``` 
(for the declaration of import)
 
2)
`I'm not sure what to parse here when looking at "import".` (for the use of import)

(Happy to help if more details needed, beta testing, etc)

**Comment by cristianoc** [comment]
See release notes for the compiler.
import was an experimental syntax never officially supported and has now been removed.

**Comment by zth** [comment]
I don't think this is related to the dedicated import syntax experiment that was removed. I think 2 things are at play here:

1) Formatting. A while back we introduced the ability to format files outside of ReScript projects. Formatting outside of a ReScript project uses the parser directly, which we vendor in the extension. This is because having no ReScript project setup means there's no ReScript binary to use for formatting, so we need to use something else.

The vendored parser is updated quite frequently, and is not tied to a specific ReScript version. It's instead typically a very recent, often unreleased version.

However, formatting inside of a properly setup `rescript` project should be using that project's _installed_ formatter, and not the vendored parser. So, for you, it should be formatting on save using `rescript@9.1.4`. If that's not the case, then that's a bug, which luckily should be fairly easy to fix. I can have a quick look at that soon and try to replicate.

2) This looks like the formatter is removing `\""`. @remitbri would you mind trying to verify whether this happens for you for _any_ escaped identifier, or just for `import` specifically?

**Comment by remitbri** [comment]
@zth For any escaped identifier. E.g a `switch editorState.\"export"` or `type \"foobar"` become `switch editorState.export` or `type foobar`

**Comment by cristianoc** [comment]
> @zth For any escaped identifier. E.g a `switch editorState.\"export"` or `type \"foobar"` become `switch editorState.export` or `type foobar`

Would you open an issue in the syntax repo? This affects latest syntax.

**Comment by cristianoc** [comment]
Other than that, is the rest sufficiently clear? If so this issue can be closed.

**Comment by remitbri** [comment]
@cristianoc There's also the fact that formatting inside of a properly setup rescript project should be using that project's installed formatter (see @zth's reply). Shall I open a new issue? Or is this one enough as is?

**Comment by cristianoc** [comment]
It is using the installed formatted.

**Comment by remitbri** [comment]
> It is using the installed formatted.

…then there's a detection issue?

**Comment by cristianoc** [comment]
Possibly. Try with a hello world project and if the issue remains post it here.

**Comment by remitbri** [comment]
I did have the formatting issue with a simple project. See https://gist.github.com/remitbri/7ca472afe4b64a6af167b20250d58c5c

**Comment by cristianoc** [comment]
Here's the fix: https://github.com/rescript-lang/rescript-vscode/pull/498

@zth we might need to issue a patched release soon-ish, as soon as we have given it enough time to collect other feedback

**Comment by cristianoc** [comment]
Thanks a lot @remitbri for the report.
