### ISSUE TITLE
Line breaks in documentation comments aren't formatted when displayed

### ISSUE THREAD

**Issue by zth** [rescript-lang/rescript-vscode#53]
Version `1.0.2` on macOS.

It seems documentation written with `@ocaml.doc()` doesn't format properly when shown in VSCode. This example code:

```rescript
@ocaml.doc(`This is a comment that's supposed to show up when hovering the value below. Hover this binding inside of DocIssues.res.

Note that line breaks are displayed as \n rather than as an actual line break when hovering.

## That fact seems to...
...break some of the markdown capabilities too.
`)
let getTestInt = () => 123
```

...gives this result:
![image](https://user-images.githubusercontent.com/1457626/103149787-12f53800-476d-11eb-9cfb-79884f278ab6.png)

Notice that line breaks are printed as-is rather than as line breaks. Unsure whether this is the main issue/only issue. However, when broken line breaks do not interfere, markdown formatting etc seems to work just fine.

**Comment by amiralies** [comment]
The point here is that interpolated strings have different behavour when escpaing special characters
```rescript
let foo = `foo
bar`
```
is being parsed into `"foo\\nbar"`. this is not suppored by ocaml doc parser. @IwanKaramazow can confirm if this is expected behaviour.

it should be ok using normal strings `""`.
![image](https://user-images.githubusercontent.com/13261088/103583353-d35ce780-4ef4-11eb-8c20-ffbd47b1f802.png)

Note: note that ocamldoc is not supported as first class in rescript, in future this will improve.

**Comment by zth** [comment]
But using normal strings won't work with unicode?

**Comment by amiralies** [comment]
Hmm, that's a specific use case, maybe @IwanKaramazow can help.
But again, ocaml doc is not supported properly in rescript and there's a plan for a friendly first-class in-code doc support for rescript.

**Comment by zth** [comment]
Ok, so to summarize so far:
- Multiline doc strings will work fine with regular strings `""`
- Multiline interpolation won't
- `@ocaml.doc` isn't necessarily supported (although it does seem to work). At some point there might be a first class code doc support in ReScript itself

So, as of now it'll work as long as you don't need unicode in your doc strings. Does that sound about right?

**Comment by zth** [comment]
I'm closing this since I got my question answered.
