### ISSUE TITLE
Syntax highlighting of nested comments is broken

### ISSUE THREAD

**Issue by d4h0** [rescript-lang/rescript-vscode#67]
Hi,

Syntax highlighting of nested comments is broken:

```ReScript
/*
let foo = 1
/*
let bar = 1
*/
let baz = 1
*/
```

GitHub has the same problem, so the code block above is a good demonstration. The compiler seems to support nested comments.

**Comment by chenglou** [comment]
Let's say that the compiler doesn't support nested comment anymore btw. In the current situations regarding the syntax and various toolings, nested comment isn't a safe assumption to make.

Though the highlighting should be fixed. Thanks for the report! Done just now

**Comment by d4h0** [comment]
> Let's say that the compiler doesn't support nested comment anymore btw. In the current situations regarding the syntax and various toolings, nested comment isn't a safe assumption to make.

Oh, really? That's too bad. I think, nested comments are extremely useful (mostly when debugging by uncommenting code that has comments itself).

Isn't it pretty easy to parse nested comments?

> Though the highlighting should be fixed.

Thanks!

**Comment by chenglou** [comment]
Your debugging will still work either way, since it doesn’t rely on knowing about nested comments. All the code sees is that there’s a bigger region of code commented out.

Parsing nested comment can be done. But this will now be a sometime confusing parse error:

```
/*
  hi /* bye
*/
```

ironically that might trip up your debugging workflow.

**Comment by d4h0** [comment]
That makes sense, thank you.
