### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by jacobp100** [rescript-lang/rescript-vscode#91]
I'm getting a lot of the _start build_ dialogues, similar to #23 - but unlike that issue, I think is more due to the fact I have a monorepo.

The repo is https://github.com/jacobp100/technicalc-core

Whenever I open a file in one of the sub-projects, the `bsb.lock` file gets created for that project only, and gets deleted once I close all the files in that project.

**Comment by chenglou** [comment]
Hey Jacob, sorry for the late reply. I'm actually rethinking this whole in-editor `bsb -w` thing... Still problematic for you right now right?

**Comment by mbergal** [comment]
FWIW, I've tried to use this hidden build and Problems panel for past few weeks and reverted to running `bsb` in the integrated terminal. I think there were several problems:

1. PPX errors and bsb errors like cycling dependencies don't show in Problems panel.
2. Errors in Problems panel are harder to parse since they are not indented and not color highlighted. 

I think there were others but I don't remember what they were. 

This is not to say that I find running `bsb -w` in the integrated terminal a good UX.

**Comment by cristianoc** [comment]
Feel free to reopen with a repro.
